build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - export SPARK_TOKEN=$$SPARK_TOKEN
            - export SPARK_ROOM=$$SPARK_ROOM
            - python testing.py

publish:
    docker:
        repo: $$DOCKER_USERNAME/ahod_server1
        tag: latest
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        when:
            branch: "master"

    docker:
        repo: $$DOCKER_USERNAME/ahod_server1
        tag: dev
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        when:
            branch: "dev"

deploy:
    webhook:
        commands:
            - export SPARK_TOKEN=$$SPARK_TOKEN
            - export SPARK_ROOM=$$SPARK_ROOM
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$MANTL_USERNAME
            password: $$MANTL_PASSWORD
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/ahod/iot-server/restart?force=true
        when:
            branch: "master"

    webhook:
        commands:
            - export SPARK_TOKEN=$$SPARK_TOKEN
            - export SPARK_ROOM=$$SPARK_ROOM
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$MANTL_USERNAME
            password: $$MANTL_PASSWORD
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/ahod/iot-server-dev/restart?force=true
        when:
branch: "dev"